dist: trusty
os:
  - linux
  # - osx CoreCLR does not support OS X 10.9 (yet)
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
# before_install:
#   - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
script:
  - ./tools/coreclr-build.sh -diagnostics