language: csharp
dist: trusty
os:
  - linux
  # - osx CoreCLR does not support OS X 10.9 (yet)
mono:
  - 4.0.5
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
    - master
    - release
    - dev
    - /^ci-.*$/

# before_install:
#   - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
env: KOREBUILD_TEST_SKIPMONO=1
script:
  - ./build.sh verify
